version: '3.7'

services:
  api-tests-ozon:
    image: python:3.12-slim
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: pytest -s api_tests/tests/ozon_tests
    working_dir: /app
#    environment:
#      - CF_ACCESS_CLIENT_ID=${CF_ACCESS_CLIENT_ID}
#      - CF_ACCESS_CLIENT_SECRET=${CF_ACCESS_CLIENT_SECRET}