version: '3.7'

services:
  api-tests-ozon:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POETRY_GROUP=ozon
    image: test-automation:ozon
    volumes:
      - ./:/app
    command: poetry run pytest -s api_tests/services/ozon/tests
    working_dir: /app